In [88]:
import torch

In [89]:
torch.tensor(9)

tensor(9)

In [90]:
revenue = torch.tensor([100,120,90,75])
revenue

tensor([100, 120,  90,  75])

In [91]:
revenue[0], revenue[1]

(tensor(100), tensor(120))

In [92]:
revenue[:3]

tensor([100, 120,  90])

In [93]:
#Sales data for Quater 1(Matrix 1)
#Row -> different product, Col->different region

q1 = torch.tensor([
    [200, 220, 250], #Product A (iphone)
    [150, 180, 210], #Product B (ipad)
    [300, 330, 360] #Product C (MacBook)
])

q2 = torch.tensor([
    [209, 231, 259], #Product A (iphone)
    [150, 192, 222], #Product B (ipad)
    [310, 340, 375] #Product C (MacBook)
])

In [94]:
#Total Sales
q1+q2

tensor([[409, 451, 509],
        [300, 372, 432],
        [610, 670, 735]])

In [95]:
#Growth
q2-q1

tensor([[ 9, 11,  9],
        [ 0, 12, 12],
        [10, 10, 15]])

In [96]:
#Percentage Growth
(q2-q1)*100/q1

tensor([[4.5000, 5.0000, 3.6000],
        [0.0000, 6.6667, 5.7143],
        [3.3333, 3.0303, 4.1667]])

In [97]:
#10% of units returned
return_rate = 0.1
return_rate * q1

tensor([[20., 22., 25.],
        [15., 18., 21.],
        [30., 33., 36.]])

In [98]:
# profit per unit is given product and region wise
# calculate total profit for all units per region, per product
profit_per_unit = torch.tensor([
    [30,27,25],
    [20,18,17],
    [45,38,39]
])

profit_per_unit * q1

tensor([[ 6000,  5940,  6250],
        [ 3000,  3240,  3570],
        [13500, 12540, 14040]])

In [99]:
product_prices = torch.tensor([[1100, 450, 1500]])
product_prices

tensor([[1100,  450, 1500]])

In [100]:
torch.matmul(product_prices, q1)

tensor([[737500, 818000, 909500]])

In [101]:
#transpose
product_prices.t() 

tensor([[1100],
        [ 450],
        [1500]])

In [103]:
prices_by_region = q1 * product_prices.t() 
prices_by_region

tensor([[220000, 242000, 275000],
        [ 67500,  81000,  94500],
        [450000, 495000, 540000]])

In [106]:
prices_by_region.sum(dim=0)

tensor([737500, 818000, 909500])

In [107]:
# Create portfolio composition matrix (3x3)
# Rows: Different portfolios (P1, P2, P3)
# Columns: Asset allocation (Stocks, Bonds, Real Estate)
portfolio_composition = torch.tensor([
    [100.0, 50.0, 30.0],  # P1
    [80.0, 70.0, 20.0],   # P2
    [60.0, 40.0, 90.0]    # P3
], dtype=torch.float32)

# Create price change matrix (3x3)
# Rows: Assets (Stocks, Bonds, Real Estate)
# Columns: Economic scenarios (Growth, Neutral, Recession)
price_changes = torch.tensor([
    [1.15, 1.05, 0.85],  # Stocks
    [1.05, 1.02, 1.10],  # Bonds
    [1.10, 1.00, 0.90]   # Real Estate
], dtype=torch.float32)

values = torch.matmul(portfolio_composition, price_changes)
values

tensor([[200.5000, 186.0000, 167.0000],
        [187.5000, 175.4000, 163.0000],
        [210.0000, 193.8000, 176.0000]])

In [108]:
83 * values

tensor([[16641.5000, 15438.0000, 13861.0000],
        [15562.5000, 14558.1992, 13529.0000],
        [17430.0000, 16085.3994, 14608.0000]])

In [109]:
torch.cuda.is_available()

True

In [110]:
if torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")

In [111]:
device

device(type='cuda')

In [112]:
# Simulating customer data with 1 million customers and 3 features (age, spending score, income)
customer_data = torch.rand(1_000_000, 3, device=device)
customer_data.shape

torch.Size([1000000, 3])

In [113]:
customer_data[:5]

tensor([[0.1217, 0.0244, 0.2345],
        [0.1948, 0.0121, 0.7437],
        [0.8616, 0.3013, 0.0102],
        [0.9444, 0.1350, 0.5052],
        [0.3720, 0.6668, 0.0175]], device='cuda:0')

In [115]:
customer_data[:,1]

tensor([0.0244, 0.0121, 0.3013,  ..., 0.6031, 0.7093, 0.6050], device='cuda:0')

In [116]:
high_spending_customer = customer_data[customer_data[:,1] > 0.5] 
high_spending_customer

tensor([[0.3720, 0.6668, 0.0175],
        [0.0055, 0.5367, 0.1183],
        [0.9065, 0.5456, 0.9527],
        ...,
        [0.8247, 0.6031, 0.5008],
        [0.3250, 0.7093, 0.8296],
        [0.9086, 0.6050, 0.8567]], device='cuda:0')

In [117]:
high_spending_customer.shape

torch.Size([500851, 3])

In [118]:
high_spending_customer.to("cpu")

tensor([[0.3720, 0.6668, 0.0175],
        [0.0055, 0.5367, 0.1183],
        [0.9065, 0.5456, 0.9527],
        ...,
        [0.8247, 0.6031, 0.5008],
        [0.3250, 0.7093, 0.8296],
        [0.9086, 0.6050, 0.8567]])